apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
    - v1beta1
    - v1
  clientConfig:
    caBundle: ""
    service:
      name: admission-webhook-service     # Changed from 'service'
      namespace: kubeflow                 # Add this line if it's missing
      path: /apply-poddefault
  sideEffects: None
  failurePolicy: Fail
  name: $(podDefaultsDeploymentName).kubeflow.org
  namespaceSelector:
    matchLabels:
      app.kubernetes.io/part-of: kubeflow-profile
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
