---
- name: Prepare nodes for Kubernetes
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - apt-transport-https
          - software-properties-common
          - python3-pip
        state: present

    - name: Install pip packages
      pip:
        name:
          - ansible
          - jmespath

    - name: Ensure SSH keys are present
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/authorized_keys
        owner: "{{ ansible_user }}"
        mode: '0600'

    - name: Disable swap (required for Kubernetes)
      command: swapoff -a
      when: ansible_facts['swaptotal_mb'] > 0

    - name: Ensure swap is disabled permanently
      lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent
