replicaCount: 1

image:
  repository: gcr.io/google_containers/echoserver
  pullPolicy: Always
  tag: "1.10"

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: echo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
